[package]
name = "day4"
version = "0.1.0"
edition = "2021"

[dependencies]
array2d = "0.3.2"
itertools = "0.13.0"
lazy_static = "1.5.0"
rayon = "1.10.0"
regex = "1.11.1"

shared = { path = "../shared" }
